from pathlib import Path
p=Path('/mnt/data/work/app.js')
s=p.read_text()
s=s.replace("{id:'corporativo-azul',name:'Corporativo Azul',desc:'Profesional y limpio',accent:'#1f5f8b',soft:'#eaf3f8',ink:'#17324d'},","{id:'corporativo-azul',name:'Corporativo Azul',desc:'Profesional y limpio',accent:'#1f5f8b',soft:'#eaf3f8',ink:'#17324d',layout:'classic'},")
s=s.replace("{id:'azul-premium',name:'Azul Premium',desc:'Elegante y ejecutivo',accent:'#123b66',soft:'#edf3f8',ink:'#102a43'},","{id:'azul-premium',name:'Azul Premium',desc:'Elegante y ejecutivo',accent:'#123b66',soft:'#edf3f8',ink:'#102a43',layout:'premium'},")
s=s.replace("{id:'negro-dorado',name:'Negro & Dorado',desc:'Premium y sobrio',accent:'#9a7424',soft:'#f7f1e4',ink:'#252525'},","{id:'negro-dorado',name:'Negro & Dorado',desc:'Premium y sobrio',accent:'#9a7424',soft:'#f7f1e4',ink:'#252525',layout:'dark'},")
s=s.replace("{id:'esmeralda',name:'Esmeralda',desc:'Moderno y fresco',accent:'#18745c',soft:'#eaf7f2',ink:'#153b32'},","{id:'esmeralda',name:'Esmeralda',desc:'Moderno y fresco',accent:'#18745c',soft:'#eaf7f2',ink:'#153b32',layout:'band'},")
s=s.replace("{id:'gris-industrial',name:'Gris Industrial',desc:'Fuerte y técnico',accent:'#4c5965',soft:'#eef1f3',ink:'#27313a'},","{id:'gris-industrial',name:'Gris Industrial',desc:'Fuerte y técnico',accent:'#4c5965',soft:'#eef1f3',ink:'#27313a',layout:'industrial'},")
s=s.replace("{id:'minimalista',name:'Minimalista',desc:'Blanco y discreto',accent:'#3d4a55',soft:'#f4f5f6',ink:'#20262b'},","{id:'minimalista',name:'Minimalista',desc:'Blanco y discreto',accent:'#3d4a55',soft:'#f4f5f6',ink:'#20262b',layout:'minimal'},")
s=s.replace("{id:'azul-cielo',name:'Azul Cielo',desc:'Claro y contemporáneo',accent:'#277ea8',soft:'#edf8fc',ink:'#1d4356'},","{id:'azul-cielo',name:'Azul Cielo',desc:'Claro y contemporáneo',accent:'#277ea8',soft:'#edf8fc',ink:'#1d4356',layout:'modern'},")
s=s.replace("{id:'terracota',name:'Terracota',desc:'Cálido y profesional',accent:'#a7543c',soft:'#fbefeb',ink:'#4a2a23'},","{id:'terracota',name:'Terracota',desc:'Cálido y profesional',accent:'#a7543c',soft:'#fbefeb',ink:'#4a2a23',layout:'editorial'},")
s=s.replace("{id:'borgona',name:'Borgoña Ejecutivo',desc:'Distintivo y elegante',accent:'#7c2838',soft:'#f8ecef',ink:'#431923'},","{id:'borgona',name:'Borgoña Ejecutivo',desc:'Distintivo y elegante',accent:'#7c2838',soft:'#f8ecef',ink:'#431923',layout:'executive'},")
s=s.replace("{id:'oceano',name:'Océano',desc:'Moderno y profundo',accent:'#176b82',soft:'#eaf5f7',ink:'#163943'},","{id:'oceano',name:'Océano',desc:'Moderno y profundo',accent:'#176b82',soft:'#eaf5f7',ink:'#163943',layout:'split'},")
s=s.replace("{id:'grafito',name:'Grafito',desc:'Serio y moderno',accent:'#343b43',soft:'#eef0f2',ink:'#20252a'},","{id:'grafito',name:'Grafito',desc:'Serio y moderno',accent:'#343b43',soft:'#eef0f2',ink:'#20252a',layout:'grid'},")
s=s.replace("{id:'arena',name:'Arena Premium',desc:'Cálido y refinado',accent:'#8b6b43',soft:'#f7f1e8',ink:'#3e3428'}];","{id:'arena',name:'Arena Premium',desc:'Cálido y refinado',accent:'#8b6b43',soft:'#f7f1e8',ink:'#3e3428',layout:'soft'}];")
# docHTML root class
s=s.replace(" return `\n <div class=\"doc-head\">", " const tpl=currentTemplate();\n return `\n <div class=\"doc-shell doc-layout-${esc(tpl.layout||'classic')}\">\n <div class=\"doc-head\">")
s=s.replace(" <div class=\"doc-foot\">SK House Construction</div>\n `;", " <div class=\"doc-foot\">SK House Construction</div>\n </div>\n `;")
# PDF page header replace
old="""      const pageHeader=()=>{\n        if(pdfLogoData)addImage(pdfLogoData,'JPEG',M,y,20,20,'sklogo');\n        addText('SK House Construction',M+24,y+5,13,'bold',blue);\n        if(company.holder) addText(String(company.holder),M+24,y+10,7,'bold',blue);\n        let cy=y+13;\n        [['Cel: ',company.phone],['Correo: ',company.email],['Dirección: ',company.address],['RFC: ',company.rfc]].forEach(([a,b])=>{if(b){addText(a+String(b),M+24,cy,5.8,'normal',gray);line(M+24,cy+1.2,M+96,cy+1.2,[226,232,239],.18);cy+=3.5}});\n        addText(d.type==='quote'?'COTIZACIÓN':'NOTA DE VENTA',W-M,y+5,9,'bold',blue,{align:'right'});\n        addText('Folio: '+(d.folio||''),W-M,y+9,6.5,'bold',[55,65,80],{align:'right'});\n        addText('Inicio: '+pdfDate(d.dateStart||d.date||''),W-M,y+13,6.2,'normal',gray,{align:'right'});\n        addText('Vencimiento: '+pdfDate(d.dateEnd||d.date||''),W-M,y+17,6.2,'normal',gray,{align:'right'});\n        addText(String(d.status||'Pendiente'),W-M,y+21,6.2,'bold',gold,{align:'right'});\n        y+=25;line(M,y,W-M,y,blue2,.6);y+=4;\n      };"""
new="""      const pageHeader=()=>{\n        const layout=currentTemplate().layout||'classic';\n        if(layout==='dark'){pdf.setFillColor(...blue);pdf.rect(sx(0),sy(y-1),sw(W),sw(28),'F');}\n        if(layout==='band'){pdf.setFillColor(...blue);pdf.rect(sx(M),sy(y-1),sw(4),sw(25),'F');}\n        if(layout==='industrial'){pdf.setFillColor(...[38,45,52]);pdf.rect(sx(M),sy(y-1),sw(CW),sw(24),'F');}\n        if(layout==='premium'){pdf.setFillColor(...[248,249,251]);pdf.roundedRect(sx(M),sy(y-1),sw(CW),sw(25),2,2,'F');}\n        if(pdfLogoData)addImage(pdfLogoData,'JPEG',M+(layout==='band'?7:2),y+(layout==='dark'?2:0),20,20,'sklogo');\n        const textColor=(layout==='dark'||layout==='industrial')?[255,255,255]:blue;\n        const metaColor=(layout==='dark'||layout==='industrial')?[235,240,245]:gray;\n        const tx=M+(layout==='band'?31:26);\n        addText('SK House Construction',tx,y+5,13,'bold',textColor);\n        if(company.holder) addText(String(company.holder),tx,y+10,7,'bold',textColor);\n        let cy=y+13;\n        [['Cel: ',company.phone],['Correo: ',company.email],['Dirección: ',company.address],['RFC: ',company.rfc]].forEach(([a,b])=>{if(b){addText(a+String(b),tx,cy,5.8,'normal',metaColor);cy+=3.5}});\n        addText(d.type==='quote'?'COTIZACIÓN':'NOTA DE VENTA',W-M,y+5,9,'bold',textColor,{align:'right'});\n        addText('Folio: '+(d.folio||''),W-M,y+9,6.5,'bold',metaColor,{align:'right'});\n        addText('Inicio: '+pdfDate(d.dateStart||d.date||''),W-M,y+13,6.2,'normal',metaColor,{align:'right'});\n        addText('Vencimiento: '+pdfDate(d.dateEnd||d.date||''),W-M,y+17,6.2,'normal',metaColor,{align:'right'});\n        addText(String(d.status||'Pendiente'),W-M,y+21,6.2,'bold',gold,{align:'right'});\n        y+=27;\n        if(layout==='minimal')line(M,y,W-M,y,[190,198,206],.35);\n        else if(layout==='grid')line(M,y,W-M,y,[90,98,106],1.1);\n        else line(M,y,W-M,y,blue2,.6);\n        y+=4;\n      };"""
if old not in s: raise SystemExit('header block not found')
s=s.replace(old,new)
# Table header accent with special layouts
s=s.replace("addText('CONCEPTOS',M,y,7.5,'bold',blue);y+=3;pdf.setFillColor(...blue2);pdf.rect(sx(M),sy(y),sw(CW),sw(6),'F');", "const layout=currentTemplate().layout||'classic'; addText('CONCEPTOS',M,y,7.5,'bold',blue);y+=3; if(layout==='minimal'||layout==='soft') { pdf.setFillColor(...[246,248,250]); } else if(layout==='dark'||layout==='industrial') { pdf.setFillColor(...[38,45,52]); } else { pdf.setFillColor(...blue2); } pdf.rect(sx(M),sy(y),sw(CW),sw(6),'F');")
# Client box styling conditional
s=s.replace("rect(M,y,CW,clientH,light,border);addText('DATOS DEL CLIENTE',M+4,y+5,7.2,'bold',blue);line(M+4,y+7,W-M-4,y+7,border,.25);", "const clientFill=(layout==='minimal'||layout==='soft')?[252,252,252]:layout==='dark'?[248,248,248]:light; const clientStroke=(layout==='grid'||layout==='industrial')?blue2:border; rect(M,y,CW,clientH,clientFill,clientStroke,layout==='grid'?0:0.7); if(layout==='band'||layout==='executive'){pdf.setFillColor(...blue2);pdf.rect(sx(M),sy(y),sw(3),sw(clientH),'F');} addText('DATOS DEL CLIENTE',M+4,y+5,7.2,'bold',blue);line(M+4,y+7,W-M-4,y+7,border,.25);")
p.write_text(s)
